const ACTIONS = {
  ADD_RECIPE: ' ADD_RECIPE',
  DELETE_RECIPE: 'DELETE_RECIPE',
  UPDATE_RECIPES: 'UPDATE_RECIPES',
  ADD_INGREDIENT: ' ADD_INGREDIENT',
  DELETE_INGREDIENT: 'DELETE_INGREDIENT',
  UPDATE_INGREDIENT: 'UPDATE_INGREDIENT'
};

export default ACTIONS;
